[workspace]
members = [
    "code/executor",
    "code/launcher",
    "code/openai",
    "code/utils",
    "code/builder",
]

[workspace.dependencies]
executor = { path = "code/executor" }
launcher = { path = "code/launcher" }
openai = { path = "code/openai" }
utils = { path = "code/utils" }
builder = { path = "code/builder"}
