[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.28"
tokio = { version = "1.28.0", features = ["full"] }
anyhow = "1.0.70"
regex = "1.8.1"
once_cell = "1.17.1"
tokio-stream = "0.1.14"

[dev-dependencies]
itertools = "0.10.5"