[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.26"
tokio = { version = "1.26.0", features = ["full"] }
anyhow = "1.0.70"
regex = "1.7.3"
once_cell = "1.17.1"
tokio-stream = "0.1.12"

[dev-dependencies]
itertools = "0.10.5"