[package]
name = "executor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.68"
derive-discriminant.workspace = true
derive-build.workspace = true
ron = "0.8.0"
tokio = { version = "1.27.0", features = ["full"] }
utils.workspace = true
