[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
derive-discriminant = "0.1.1"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.3.1", features = ["serde", "v4"] }
